name: snaplant_mobile
description: SnapPlant 植物図鑑モバイルアプリ

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter

  # UI & Material Design
  cupertino_icons: ^1.0.6
  material_color_utilities: ^0.11.1

  # HTTP通信
  http: ^1.2.0
  dio: ^5.4.0

  # 画像処理
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1

  # データ保存
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0

  # ユーティリティ
  uuid: ^4.3.3
  intl: ^0.19.0

  # ナビゲーション
  go_router: ^13.2.0

  # 状態管理
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf
        - asset: fonts/Roboto-Medium.ttf
          weight: 500
        - asset: fonts/Roboto-Bold.ttf
          weight: 700