name: Deploy to Production

on:
  push:
    branches: [ main ]
    paths:
      - 'api/**'
      - '.github/workflows/**'
  workflow_dispatch: # 手動実行も可能

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './api'
  NODE_VERSION: '20.x'

jobs:
  # まずCIワークフローを呼び出し
  test:
    uses: ./.github/workflows/ci.yml
    permissions:
      actions: read
      contents: read
      security-events: write

  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    environment: 
      name: production
      url: ${{ steps.deploy.outputs.app-url }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/package-lock.json

    - name: Install dependencies
      run: |
        cd ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        npm ci

    - name: Build for production
      run: |
        cd ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        npm run build

    - name: Clean dev dependencies
      run: |
        cd ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        npm prune --production

    - name: Deploy to Azure Functions
      id: deploy
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ secrets.AZURE_FUNCTIONAPP_NAME }}
        package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
        scm-do-build-during-deployment: true
        enable-oryx-build: true

    - name: Health Check
      run: |
        # Function Appが起動するまで少し待つ
        sleep 30
        
        # ヘルスチェックエンドポイントがあれば確認
        APP_URL="https://${{ secrets.AZURE_FUNCTIONAPP_NAME }}.azurewebsites.net"
        echo "Checking health of: $APP_URL"
        
        # Function Appの基本的な応答確認
        if curl -f -s "$APP_URL" > /dev/null; then
          echo "✅ Function App is responding"
        else
          echo "⚠️ Function App may not be fully ready yet"
        fi

    - name: Post-deployment notification
      if: always()
      run: |
        if [ "${{ job.status }}" == "success" ]; then
          echo "🚀 Deployment to production completed successfully!"
          echo "App URL: https://${{ secrets.AZURE_FUNCTIONAPP_NAME }}.azurewebsites.net"
        else
          echo "❌ Deployment failed"
        fi